### ISSUE TITLE
About the Input

### ISSUE THREAD

**Issue by wanyding** [sagarvegad/Video-Classification-CNN-and-LSTM-#2]
Hi, I am new to LSTM, and I think there are some details in your codes I find it hard to understand. 

First, I don't understand why we should set the shuffle=True, after all, we will feed the frame sequence into LSTM later, and I guess the sequence should be arrange by the time order, so it seems unreasonable to shuffle the image before training as it will break the order.

Also, the batch size is set as 128, I am wondering if you mean a batch of images belongs to the same video? After training those batches on vgg, the result batches are sent to LSTM, so I guess a batch of images are seen as frame sequence from the same video, am I right? 

Please help me, thank you!

**Comment by amna-ai** [comment]
Did you got the idea? If yes then enlighten me too 😓
